
<div class="menu">
                <ul> 
                    <li><a href="#"><font color="#FFFFFF">Home</font></a></li>
                    <li><a href="#"><font color="#FFFFFF">About Us</font></a></li>
                    <li><a href="#"><font color="#FFFFFF">Departments</font></a></li>
                    <li><a href="#"><font color="#FFFFFF">Gallery</font></a></li>
                    <li><a href="#"><font color="#FFFFFF">Contact Us</font></a></li>
                </ul>