<div class="login_home">
    <a href="login/login">Login</a>&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;<a href="login/signup">Sign Up</a>
</div>
<div class="news_events">
    
</div>

<div class="image_home">
<img src="/images/image-slider-2.jpg">
</div>
<div class="pagecontent">
<div class="pagecontent_left">
    <h3> Welcome </h3> 
<?php print_r($this->listdata['page_content']); ?>
</div>
<div class="pagecontent_right">
<h5>Message from the Principal</h5>
<?php print_r($this->listdata1['page_content']); ?>
</div>
</div>
                
           