
<div class="menu">
                <ul> 
                    <li><a href="/front/home"><font color="#FFFFFF">Home</font></a></li>
                    <li><a href="/front/aboutus"><font color="#FFFFFF">About Us</font></a></li>
                    <li><a href="/front/department"><font color="#FFFFFF">Departments</font></a></li>
                    <li><a href="/front/gallery"><font color="#FFFFFF">Gallery</font></a></li>
                    <li><a href="/front/contactus"><font color="#FFFFFF">Contact Us</font></a></li>
                </ul>
</div>