
<div class="menu">
                <ul> 
                    <li><a href="/"><font color="#FFFFFF">Home</font></a></li>
                    <li><a href="/index/aboutus"><font color="#FFFFFF">About Us</font></a></li>
                    <li><a href="/index/department"><font color="#FFFFFF">Departments</font></a></li>
                    <li><a href="/index/gallery"><font color="#FFFFFF">Gallery</font></a></li>
                    <li><a href="/index/contactus"><font color="#FFFFFF">Contact Us</font></a></li>
                </ul>
</div>