<div class="dashtop_left">
    Welcome &nbsp;<?php echo $this->username ?>&excl; &nbsp; This is your dashboard
</div>
<div class="dashtop_right">
    <a href="logout">Logout</a>
</div>
<div class="clear"></div>

<div class="dash_content">
            <table>
                <tr>
                    <td><a href="#" align="center"><img src="/images/user-management_3.jpg" width="250px" height="250px"></a><br>
                        <h4 align="center"><a href="#">User Management</a></h4>
                    </td>
                    <td><a href="showimages" align="center"><img  src="/images/splash_home_gallery.png" width="250px" height="250px"></a><br>
                        <h4 align="center"><a href="showimages">Gallery Management</a></h4>
                    </td>
                    <td><a href="showcontents" align="center"><img  src="/images/CMS-image_1.jpg" width="250px" height="250px"></a><br>
                        <h4 align="center"><a href="showcontents">CMS</a></h4>
                    </td>
                </tr>
            </table>
</div>