<div id="loginfrm">
    <center>Welcome &nbsp;<?php echo $this->username ?>,<br> This is your dashboard<br>
<div id="logout"><a href="../login/logout">Logout</a></div></center>
    <div class="top_icons">
<a href='addcontent'><img src="../images/action_add.gif"></a>&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;
<a href='../login/dashboard'><img src="../images/action_cancel.gif"></a>
    </div>
<table width="675" cellpadding="2" cellspacing="2" border="2" align="center">

<tr>

<th><strong>Page title</strong></th>

<th><strong>Contents</strong></th>

<th><strong>Published</strong></th>

<th><strong>Action</strong></th>

<?php foreach ($this->listdata as $row): ?>
<tr>

<td><?php echo $row['page_title']?></td>

<td><?php echo $row['page_content']?></td>
<td><?php echo $row['page_publish']?></td>

<td><a href="editcontent?page_id=<?php echo $row['page_id']?>"><img src="/images/edit.png" height="25px" width="25px" alt="Edit"></a>&nbsp;&nbsp;<a href="deletecontent?page_id=<?php echo $row['page_id']?>" onclick="return confirm('Are you sure?');"><img src="/images/delete.png" height="25px" width="25px" alt="Delete" ></a></td>
</tr>

<?php endforeach; ?>

</table>
</div>